### PR TITLE
docs: await koaWebpack to register middleware

### PR DESCRIPTION
**Pull request by flisky**
I'm bitten by this  :face_with_head_bandage: , and hope nobody face it again.

### CODE REVIEW

**Comment by shellscape** [comment]
@flisky I'm sorry, but I cannot approve this PR. you've removed the pull request template (which you should never, ever do for issues or pull requests on Github), and the code changes are not correct. you may have been bitten by confusion over how `Promises` function. Using `await` will not work for all versions of Node that this module currently supports, and it is a stylistic choice as there is nothing wrong with using a `Promise.then` method.

**Comment by flisky** [comment]
I think I have a clear understanding about `Promise`, and please let me elaborate:

```
koaWebpack({}).then((middleware) => app.use(middleware))`
app.listen(port)
```

1. `koaWebpack({})` runs first
2. and then `app.listen(port)`
3. `app.use(middleware)` goes last.

However, `app.use(middleware)` has **no effect** after app starts up. So we need `await`.

I just want to emphasize it on document, and please correct me if anything goes wrong.

**Comment by flisky** [comment]
ping @shellscape

**Comment by shellscape** [comment]
See the updated README on master - those docs are the correct usage. You can also view the tests for additional usage. I've given the package some attention.

**Pull request closed without merging**
