### PR TITLE
feat: adding options.configPath

### PR DESCRIPTION
**Pull request by ianwalter**
So that koa-webpack can be further upstream than one hop from
mainModule while still maintaining some sane default functionality.

This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

If options.compiler or options.config is not specified, then koa-webpack defaults to {mainModule directory}/webpack.config.js which is usually a nice default but it doesn't work for me since I'm actually requiring koa-webpack from a module that is itself being required by the end-user application. 

As a workaround I was going to specify options.config manually but the validation logic in koa-webpack doesn't support Webpack multicompiler config since it would be an Array instead of an Object (even though it works when not manually specifying the config). I thought about submitting a PR to change the Joi validation, but couldn't get it to work and this solution seemed easier for the user.

I didn't make any doc changes, but I will if this feature will be accepted.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR :beer:

I see no reason why this shouldn't be added. I'd like to request a change to the option name: `configPath`, where that would represent the full file path for the config. That should allow for added flexibility, and remove the possibility of confusing `root` with `cwd`.

I'll get the deps updated so that analysis step will pass, you'll just have to merge upstream/master and CI should start passing.

**Comment by shellscape** [comment]
Looks good. I can merge this now, but won't be able to release until I can write a test around this. (Coverage is pretty low as it is, which is on me, but I'd rather not drop it further for new additions if I can help it). If you've got time to add one, that would be cool. No worries if not.

**Comment by shellscape** [comment]
Circling back to this. Life has been insane lately and we've gotten a major Rollup project over the finish line. I'll try to get to writing a test for this soon.

**Comment by ianwalter** [comment]
> Circling back to this. Life has been insane lately and we've gotten a major Rollup project over the finish line. I'll try to get to writing a test for this soon.

I can do it if you prefer. I randomly rediscovered this this morning and meant to mention that I can probably add one tonight. Congrats, btw, I love Rollup.

**Comment by shellscape** [comment]
Yes please!

**Comment by shellscape** [comment]
@ianwalter very much appreciate the tests!

**Pull request merged**
