### PR TITLE
fix inappropriate webpack.config.js require when using compiler option

### PR DESCRIPTION
**Pull request by olconstant**

### CODE REVIEW

**Comment by olconstant** [comment]
Because below this code, a if condition tests options.dev.publicPath, and if it is undefined, the if statement below uses the ´config´ variable to configure the publicPath, so if options.dev.publicPath is unfefined, we need the ´config´ variable for the code below:
'''
if (!options.dev.publicPath) {
  options.dev.publicPath = config.output.publicPath;
}
'''

**Comment by olconstant** [comment]
PR branch rebased to remove conflicts.

**Comment by olconstant** [comment]
Without this fix, I have to call koa-webpack this way, with an empty config Object... 
`app.use(webpackKoa({ compiler, dev, config: {} }));`

**Comment by shellscape** [comment]
thanks for reporting the issue and for putting together your PR. I chose to go a different direction to resolve this in aa46f351a90488570aaebf3a712a97c611f068b3.

**Pull request closed without merging**
