### PR TITLE
chore: upgrade deps; drop node 8

### PR DESCRIPTION
**Pull request by AviVahl**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**
- [x] **dependency upgrades**

### Motivation / Use-Case

fixes all `npm audit` failures. cleans up `node_modules` by better deduping.

closes #122 

### Breaking Changes

Drops EOL Node 8. many packages already started dropping it, so now's probably a good time.

### Additional Info

### CODE REVIEW

**Comment by AviVahl** [comment]
@shellscape heya, any chance you've got time to review this? :)

**Comment by AviVahl** [comment]
new audit failures are pending upstream releases of:
- conventional-github-releaser: https://github.com/conventional-changelog/releaser-tools
- @commitlint/config-conventional: https://github.com/conventional-changelog/commitlint

**Comment by shellscape** [comment]
@AviVahl you can nuke both of those safely.

**Comment by AviVahl** [comment]
will do :+1:

**Comment by AviVahl** [comment]
nuking these two got *144* other deps removed :o

**Comment by AviVahl** [comment]
hey again @shellscape PR is ready from end. We could use the upgrades downstream...

**Comment by shellscape** [comment]
Thanks for the continued work here. I'll get to publishing this as soon as I'm able. Traveling and will need a break to do so.

**Comment by shellscape** [comment]
v6.0.0 published

**Comment by AviVahl** [comment]
Much appreciated. I've also accepted the invitation to collaborate on the project. Thanks. Will make it a bit easier to open PRs.

**Pull request merged**
