### PR TITLE
fix: `options.compiler` is required

### PR DESCRIPTION
**Pull request by JounQin**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

https://github.com/shellscape/koa-webpack/blob/master/lib/index.js#L30-L40

`options.compiler` is used after initialize, if we provide `options.config` without `options.compiler`, it will throw an error at https://github.com/shellscape/koa-webpack/blob/master/lib/index.js#L36, so we need to set `options.compiler`.

### Breaking Changes

None

### Additional Info

Update usage document

### CODE REVIEW

**Comment by shellscape** [comment]
Please please please don't remove portions of the issue template. I'll be happy to review when you update the PR with the missing info and a better explanation of the PR.

**Comment by shellscape** [comment]
I don't understand this change. `options.compiler` doesn't exist anywhere in the codebase after the last release.

**Comment by JounQin** [comment]
@shellscape https://github.com/shellscape/koa-webpack/blob/master/lib/index.js#L30
It is used here.

**Comment by shellscape** [comment]
Interesting. Must pass as a false positive. That's going to need a different fix than what's in this PR, which I'll push in a bit.

**Comment by JounQin** [comment]
OK, I will close this PR then.

**Comment by shellscape** [comment]
Thanks for bringing that to attention though

**Pull request closed without merging**
